import assert from 'node:assert/strict';
import { mkdirSync, writeFileSync, readFileSync, rmSync, existsSync } from 'node:fs';
import { execFileSync } from 'node:child_process';

const [binary, root] = process.argv.slice(2);
assert.ok(binary && root, 'usage: node smoke.mjs BINARY EMPTY_WORKSPACE');
mkdirSync(root, { recursive: true });
execFileSync('git', ['init', '-q', root]);
const run = (...args) => JSON.parse(execFileSync(binary, ['--root', root, ...args], { encoding: 'utf8' }));
assert.equal(run('install').ready, true);
assert.equal(run('doctor').ready, true);
assert.ok(readFileSync(`${root}/AGENTS.md`, 'utf8').includes('.ori/INSTRUCTIONS.md'));
const hook = JSON.parse(execFileSync(binary, ['hook'], {input:JSON.stringify({hook_event_name:'SessionStart',source:'compact',cwd:root}),encoding:'utf8'}));
assert.equal(hook.hookSpecificOutput.hookEventName, 'SessionStart');
assert.ok(hook.hookSpecificOutput.additionalContext.includes('$ori:'));

assert.equal(existsSync(`${root}/.ori/state/index.sqlite`), false, 'setup should not create an index');
const configBefore = readFileSync(`${root}/.ori/config.json`, 'utf8');
writeFileSync(`${root}/graph/entities/search.json`, JSON.stringify({ id: 'search', name: 'Search' }));
writeFileSync(`${root}/graph/components/search-intent.json`, JSON.stringify({ id: 'search-intent', entityId: 'search', type: 'intent', text: 'Find product requirements with multilingual search.' }));
run('validate');
const graph = run('graph');
assert.equal(graph.entities[0].id, 'search');
rmSync(`${root}/.ori/projections`, { recursive: true });
run('init');
assert.equal(run('doctor').ready, true);
assert.equal(readFileSync(`${root}/.ori/config.json`, 'utf8'), configBefore);
assert.equal(run('graph').revision, graph.revision, 'repair should preserve graph revision');
const found = run('find', '--query', 'multilingual', '--lexical');
assert.equal(found.revision, graph.revision);
assert.equal(found.mode, 'lexical');
assert.ok(Array.isArray(found.hits));
assert.ok(found.hits.some(item => item.id === 'search-intent'));
const projection = run('project', '--id', 'all');
assert.equal(projection.id, 'all');
assert.ok(projection.components.some(item => item.id === 'search-intent'));
assert.equal(projection.graphRevision, graph.revision);
assert.match(projection.digest, /^[a-f0-9]{64}$/);
console.log('Ori CLI smoke passed: install, idempotent repair, doctor, chat hook, graph validation, lexical search, portable projection.');
